export const CART_REQ_DATA = 'CART_REQ_DATA';
export const CART_RECV_DATA = 'CART_RECV_DATA';
export const CART_REPEAT_RECV_DATA = 'CART_REPEAT_RECV_DATA';
export const CART_REMOVE_DATA = 'CART_REMOVE_DATA';
export const CART_RECV_ERROR = 'CART_RECV_ERROR';
