export const PORTFOLIO_REQ_DATA = 'PORTFOLIO_REQ_DATA';
export const PORTFOLIO_RECV_DATA = 'PORTFOLIO_RECV_DATA';
export const PORTFOLIO_POST_DATA = 'PORTFOLIO_POST_DATA';
export const PORTFOLIO_PUT_DATA = 'PORTFOLIO_PUT_DATA';
export const PORTFOLIO_RECV_ERROR = 'PORTFOLIO_RECV_ERROR';
